# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(blank=True, default=0, verbose_name='Antall stemmer')),
                ('winner', models.BooleanField(default=False)),
                ('candidate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='Er åpent')),
                ('current_position_is_open', models.BooleanField(default=False, verbose_name='Det er åpent for stemming')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='Navn på verv')),
                ('spots', models.IntegerField(verbose_name='Antall plasser')),
                ('total_votes', models.IntegerField(default=0)),
                ('voting_done', models.BooleanField(default=False)),
                ('candidates', models.ManyToManyField(blank=True, related_name='positions', to='elections.Candidates')),
                ('winners', models.ManyToManyField(blank=True, default=None, related_name='winners', to='elections.Candidates')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_election', to='elections.Position'),
        ),
        migrations.AddField(
            model_name='election',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='election', to='elections.Position'),
        ),
    ]
