# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='number_of_voters',
            field=models.PositiveIntegerField(default=0, verbose_name='Antall stemmesedler avgitt'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Antall stemmer'),
        ),
        migrations.AlterField(
            model_name='position',
            name='spots',
            field=models.PositiveIntegerField(default=1, verbose_name='Antall plasser'),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Totalt stemmer mottatt'),
        ),
    ]
