# Generated by Django 2.1.7 on 2019-04-29 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20181124_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blank', models.BooleanField(default=False, verbose_name='Blank stemme')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='election',
            name='current_position_is_open',
        ),
        migrations.RemoveField(
            model_name='position',
            name='number_of_voters',
        ),
        migrations.RemoveField(
            model_name='position',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='position',
            name='voting_done',
        ),
        migrations.RemoveField(
            model_name='position',
            name='winners',
        ),
        migrations.AddField(
            model_name='candidate',
            name='image_url',
            field=models.CharField(default='/static/images/blank_avatar.png', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pre_votes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Antall forhåndstemmer'),
        ),
        migrations.AddField(
            model_name='position',
            name='by_acclamation',
            field=models.BooleanField(default=False, verbose_name='Alle kandidater vant med akklamasjon'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Er valget åpent'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Valget er gjennomført'),
        ),
        migrations.AddField(
            model_name='position',
            name='number_of_prevote_tickets',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Antall personer som har forhåndsstemt'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL, verbose_name='kandidatens bruker'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Antall stemmer'),
        ),
        migrations.AlterField(
            model_name='election',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_election', to='elections.Position', verbose_name='Vervet som skal stemmes på'),
        ),
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='election', to='elections.Position', verbose_name='Verv'),
        ),
        migrations.AlterField(
            model_name='position',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='candidate_position', to='elections.Candidate', verbose_name='Kandidater som stiller'),
        ),
        migrations.AlterField(
            model_name='position',
            name='spots',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Antall plasser'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='elections.Candidate', verbose_name='Kandidatene som stemmes på'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Position'),
        ),
        migrations.AddField(
            model_name='position',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='ticket_position', to='elections.Ticket', verbose_name='Stemmesedler'),
        ),
    ]
