# Generated by Django 2.1.3 on 2019-01-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20181124_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Antall stemmer'),
        ),
    ]
