# Generated by Django 2.2.28 on 2026-08-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20190429_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='election_type',
            field=models.CharField(choices=[('ordinary', 'Vanlig valg'), ('stv', 'Preferansevalg')], default='ordinary', max_length=20),
        ),
    ]
