# Generated by Django 2.1.7 on 2019-05-05 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('duration', models.PositiveSmallIntegerField(choices=[(1, '1 time'), (2, '2 timer'), (3, '3 timer'), (4, '4 timer'), (5, '5 timer')], default=1, verbose_name='Varighet')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Varenavn')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pris')),
                ('image', models.ImageField(upload_to='shopitems', verbose_name='Bilde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('buy_without_tablet', models.BooleanField(default=False, verbose_name='Kjøp uten tabletten')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.Category', verbose_name='Kategori')),
                ('happy_hour_duplicate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Item', verbose_name='Happy Hour duplikat')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Kjøper')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Antall')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Item', verbose_name='Varenavn')),
            ],
        ),
        migrations.CreateModel(
            name='RefillReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='HC-coin')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Regnskapsfører')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill', to=settings.AUTH_USER_MODEL, verbose_name='Mottaker')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='shop.OrderItem'),
        ),
    ]
