# Generated by Django 2.1.7 on 2019-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='HC-coin'),
        ),
    ]
