# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lockers.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='LockerToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LockerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Fornavn')),
                ('last_name', models.CharField(max_length=40, verbose_name='Etternavn')),
                ('email', models.EmailField(max_length=254, validators=[lockers.validators.validate_NTNU], verbose_name='NTNU-epost')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('edited', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indefinite_locker', to='lockers.Locker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='lockers.LockerUser')),
            ],
        ),
        migrations.AddField(
            model_name='lockeruser',
            name='ownerships',
            field=models.ManyToManyField(through='lockers.Ownership', to='lockers.Locker'),
        ),
        migrations.AddField(
            model_name='lockertoken',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockers.Ownership'),
        ),
        migrations.AddField(
            model_name='locker',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definite_owner', to='lockers.Ownership'),
        ),
    ]
