# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lockeruser',
            name='first_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lockeruser',
            name='last_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
