# Generated by Django 2.2.28 on 2023-09-28 11:52

import chemie.lockers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockeruser',
            name='email',
            field=models.EmailField(max_length=254, validators=[chemie.lockers.validators.validate_NTNU], verbose_name='NTNU-epost (@stud.ntnu.no)'),
        ),
    ]
