# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='lockers.Ownership'),
        ),
        migrations.AlterField(
            model_name='lockeruser',
            name='username',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='lockers.LockerUser'),
        ),
        migrations.AlterUniqueTogether(
            name='lockeruser',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
