# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_auto_20160417_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='activation_code',
        ),
        migrations.AlterField(
            model_name='locker',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='lockers.Ownership'),
        ),
        migrations.AlterField(
            model_name='lockeruser',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lockerconfirmation',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lockers.Ownership'),
        ),
    ]
