# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_auto_20160521_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definite_owner', to='lockers.Ownership'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indefinite_locker', to='lockers.Locker'),
        ),
    ]
