# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_auto_20160423_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='lockers.Ownership'),
        ),
        migrations.AlterField(
            model_name='lockeruser',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
