# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0003_auto_20160523_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
