# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0004_ownership_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
