# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_auto_20160521_1523'),
        ('lockers', '0005_ownership_is_confirmed'),
    ]

    operations = [
    ]
