# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockeruser',
            name='internal_user',
        ),
    ]
