# Generated by Django 2.2.28 on 2024-01-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customprofile', '0018_auto_20240122_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Travelletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Land')),
                ('city', models.CharField(max_length=30, verbose_name='By')),
                ('sun', models.IntegerField(default=0, verbose_name='Solfaktor')),
                ('livingExpences', models.IntegerField(default=0, verbose_name='Levekostnader')),
                ('availability', models.IntegerField(default=0, verbose_name='Tilgjengelighet')),
                ('nature', models.IntegerField(default=0, verbose_name='Natur')),
                ('hospitality', models.IntegerField(default=0, verbose_name='Gjestfrihet')),
                ('workLoad', models.IntegerField(default=0, verbose_name='Arbeidsmengde')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customprofile.Profile', verbose_name='Bruker')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Svar')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangepage.Questions', verbose_name='Spørsmål')),
                ('travelletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='exchangepage.Travelletter')),
            ],
        ),
    ]
