# Generated by Django 2.2.28 on 2023-11-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customprofile', '0017_merge_20231015_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Travelletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('std1', models.IntegerField(default=0, verbose_name='Score, std1')),
                ('std2', models.IntegerField(default=0, verbose_name='Score, std2')),
                ('std3', models.IntegerField(default=0, verbose_name='Score, std3')),
                ('std4', models.IntegerField(default=0, verbose_name='Score, std4')),
                ('std5', models.IntegerField(default=0, verbose_name='Score, std5')),
                ('std6', models.IntegerField(default=0, verbose_name='Score, std6')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangepage.Questions')),
                ('travelletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='exchangepage.Travelletter')),
            ],
        ),
    ]
