# Generated by Django 2.2.28 on 2024-03-17 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelletter',
            name='semester',
            field=models.CharField(max_length=7, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(7)], verbose_name='Semester'),
        ),
    ]
