# Generated by Django 2.2.28 on 2024-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Spørsmål'),
        ),
    ]
