# Generated by Django 2.2.28 on 2026-04-12 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruker'),
        ),
    ]
