# Generated by Django 2.2.28 on 2023-11-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchangepage.Questions'),
        ),
    ]
