# Generated by Django 2.2.28 on 2023-11-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelletter',
            name='std1',
        ),
        migrations.RemoveField(
            model_name='travelletter',
            name='std2',
        ),
        migrations.RemoveField(
            model_name='travelletter',
            name='std3',
        ),
        migrations.RemoveField(
            model_name='travelletter',
            name='std4',
        ),
        migrations.RemoveField(
            model_name='travelletter',
            name='std5',
        ),
        migrations.RemoveField(
            model_name='travelletter',
            name='std6',
        ),
        migrations.AddField(
            model_name='travelletter',
            name='availability',
            field=models.IntegerField(default=0, verbose_name='availability'),
        ),
        migrations.AddField(
            model_name='travelletter',
            name='hospitaility',
            field=models.IntegerField(default=0, verbose_name='hospitality'),
        ),
        migrations.AddField(
            model_name='travelletter',
            name='livingExpences',
            field=models.IntegerField(default=0, verbose_name='livingExpences'),
        ),
        migrations.AddField(
            model_name='travelletter',
            name='nature',
            field=models.IntegerField(default=0, verbose_name='nature'),
        ),
        migrations.AddField(
            model_name='travelletter',
            name='sun',
            field=models.IntegerField(default=0, verbose_name='sun'),
        ),
        migrations.AddField(
            model_name='travelletter',
            name='workLoad',
            field=models.IntegerField(default=0, verbose_name='workLoad'),
        ),
    ]
