# Generated by Django 2.2.28 on 2024-02-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0002_auto_20240128_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exchangepage', verbose_name='Bilde')),
                ('travelletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exchangepage.Travelletter', verbose_name='Reisebrev')),
            ],
        ),
    ]
