# Generated by Django 2.2.28 on 2024-02-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0002_auto_20240128_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelletter',
            name='destinationInfo',
            field=models.TextField(default='Hahaha dog', max_length=2000, verbose_name='countryInfo'),
            preserve_default=False,
        ),
    ]
