# Generated by Django 2.2.28 on 2023-11-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0002_auto_20231105_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangepage.Questions'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='travelletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='exchangepage.Travelletter'),
        ),
    ]
