# Generated by Django 2.2.28 on 2023-11-13 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0002_auto_20231113_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelletter',
            old_name='hospitaility',
            new_name='hospitality',
        ),
    ]
