# Generated by Django 2.2.28 on 2024-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0003_travelletter_destinationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelletter',
            name='semester',
            field=models.CharField(default='V23', max_length=3, verbose_name='Semester'),
            preserve_default=False,
        ),
    ]
