# Generated by Django 2.2.28 on 2023-11-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0003_auto_20231107_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangepage.Questions'),
        ),
        migrations.AlterField(
            model_name='travelletter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customprofile.Profile'),
        ),
    ]
