# Generated by Django 2.2.28 on 2023-11-10 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0004_auto_20231110_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelletter',
            old_name='std1',
            new_name='Sun',
        ),
        migrations.RenameField(
            model_name='travelletter',
            old_name='std3',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='travelletter',
            old_name='std5',
            new_name='hospitality',
        ),
        migrations.RenameField(
            model_name='travelletter',
            old_name='std2',
            new_name='livingExpences',
        ),
        migrations.RenameField(
            model_name='travelletter',
            old_name='std4',
            new_name='nature',
        ),
        migrations.RenameField(
            model_name='travelletter',
            old_name='std6',
            new_name='workLoad',
        ),
        migrations.AlterField(
            model_name='experience',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangepage.Questions'),
        ),
    ]
