# Generated by Django 2.2.28 on 2024-03-19 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0004_auto_20240319_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelletter',
            name='destinationInfo',
            field=ckeditor.fields.RichTextField(max_length=700, verbose_name='Info om sted'),
        ),
    ]
