# Generated by Django 2.2.28 on 2023-11-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangepage', '0005_auto_20231110_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelletter',
            old_name='Sun',
            new_name='sun',
        ),
        migrations.AlterField(
            model_name='experience',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchangepage.Questions'),
        ),
    ]
