version: '2'
services:
  database:
    restart: always
    image: postgres:latest
    env_file: .env
    volumes:
      - ./logs/db:/var/log/postgresql
      - dbdata:/var/lib/postgresql/data

  website:
    restart: always
    build: .
    volumes:
      - ./chemie:/chemie
      - ./logs/gunicorn:/gunicorn-logfiles
      - media:/chemie/media
      - static:/chemie/static
    depends_on:
      - database
    env_file: .env
    expose:
      - "8000"

  proxy:
    build: ./nginx
    ports:
      - "1339:80"
    volumes:
      - static:/code/static
      - media:/code/media
    links:
      - website:website

  backup:
    build: ./backupjob
    volumes:
      - media:/code/media:ro
    env_file: .env
    links:
      - database:database


volumes:
  dbdata:
  media:
  static:
