version: '3.7'
services:
  # Builds database container
  database:
    restart: always
    container_name: hc_db
    image: postgres:latest
    env_file: .env
    volumes:
      - ./logs/db:/var/log/postgresql
      - dbdata:/var/lib/postgresql/data
  # Builds python code container
  website:
    restart: always
    container_name: hc_web #name to exec into
    build: .
    volumes:
      - ./chemie:/chemie
      - ./logs/gunicorn:/gunicorn-logfiles
      - /mnt/hc_ntnu_ssd/hc_ntnu_no/media:/chemie/media
      - static:/chemie/static
    depends_on:
      - database
    env_file: .env
    expose:
      - "8000"
  # Builds nginx container
  proxy:
    container_name: hc_nginx
    build: ./nginx
    ports:
      - "1339:80"
    volumes:
      - static:/code/static
      - /mnt/hc_ntnu_ssd/hc_ntnu_no/media:/code/media
    links:
      - website:website
  # Builds backup container
  backup:
    build: ./backupjob
    container_name: hc_backup
    volumes:
      - /mnt/hc_ntnu_ssd/hc_ntnu_no/media:/code/media:ro
    env_file: .env
    links:
      - database:database

# Mounted volumes persist beyond life of containers
volumes:
  dbdata:
  media:
  static:
