version: '2'
services:
  database:
    restart: always
    image: postgres:latest
    env_file: .env
    volumes:
      - ./logs/db:/var/log/postgresql
      - ./dbdata/data:/var/lib/postgresql/data
  website:
    restart: always
    build: ./chemie
    volumes:
      - ./chemie:/code
      - ./logs/gunicorn:/gunicorn-logfiles
    depends_on:
      - database
    env_file: .env
    expose:
      - "8000"
  proxy:
    build: ./nginx
    ports:
      - "1338:80"
    volumes:
      - /www/static
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - website
    links:
      - website:website
  backupjob:
    build: ./backupjob
    volumes:
      - ./backup_chemie:/etc/ssl/private/backup/chemiebackup
    volumes_from:
      - website
    env_file: .env
    links:
      - database:database


#volumes:
#  dbdata:
