<<<<<<< HEAD
# Generated by Django 2.2.10 on 2020-09-06 15:55

import ckeditor.fields
=======
# Generated by Django 2.2.13 on 2021-02-20 14:28

import ckeditor.fields
import django.core.validators
>>>>>>> c58f0a3f (Add initial migration.)
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0003_auto_20180127_0949'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Kunde')),
                ('client_mail', models.EmailField(max_length=254, verbose_name='E-post')),
                ('client_nr', models.CharField(max_length=15, verbose_name='Telefon nr.')),
                ('paid', models.BooleanField(default=False, verbose_name='Betalt?')),
                ('event', models.CharField(max_length=100, verbose_name='Arrangement')),
            ],
        ),
        migrations.CreateModel(
>>>>>>> c58f0a3f (Add initial migration.)
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='RentalObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Beskrivelse')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='rentalservice', verbose_name='Bilde')),
<<<<<<< HEAD
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.Landlord')),
            ],
        ),
=======
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Pris')),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antall')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='RentalObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentedObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antall')),
                ('rent_start', models.DateTimeField(verbose_name='Utleiestart')),
                ('rent_end', models.DateTimeField(verbose_name='Utleieslutt')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.Invoice', verbose_name='Kontrakt')),
                ('rentalObject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.RentalObject')),
            ],
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.RentalObjectType'),
        ),
>>>>>>> c58f0a3f (Add initial migration.)
    ]
