# Generated by Django 2.2.13 on 2022-03-04 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Kunde')),
                ('client_mail', models.EmailField(max_length=254, verbose_name='E-post')),
                ('client_nr', models.CharField(max_length=15, verbose_name='Telefon nr.')),
                ('paid', models.BooleanField(default=False, verbose_name='Betalt?')),
                ('event', models.CharField(max_length=100, verbose_name='Arrangement')),
            ],
        ),
        migrations.CreateModel(
            name='RentalObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Pris'),
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antall'),
        ),
        migrations.CreateModel(
            name='RentedObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antall')),
                ('rent_start', models.DateTimeField(verbose_name='Utleiestart')),
                ('rent_end', models.DateTimeField(verbose_name='Utleieslutt')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.Invoice', verbose_name='Kontrakt')),
                ('rentalObject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.RentalObject')),
            ],
        ),
        migrations.AddField(
            model_name='rentalobject',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalservice.RentalObjectType'),
        ),
    ]
