# Generated by Django 2.2.13 on 2022-03-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentedObjects',
        ),
    ]
