# Generated by Django 2.2.28 on 2024-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0003_auto_20220402_1248_squashed_0004_auto_20220402_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobject',
            name='owner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Promoterigskomiteen'), (2, 'Audio...'), (3, 'Sportskomiteen'), (4, 'Ingen')], default=4, verbose_name='Utleier'),
        ),
    ]
