# Generated by Django 2.2.28 on 2025-02-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0004_auto_20241010_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobject',
            name='owner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Promoterigskomiteen'), (2, 'Audiochromatene'), (3, 'Sportskomiteen'), (4, 'Ingen')], default=4, verbose_name='Utleier'),
        ),
    ]
