# Generated by Django 2.2.28 on 2025-09-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0005_auto_20250208_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobject',
            name='owner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Promoteringskomiteen'), (2, 'Audiochromatene'), (3, 'Sportskomiteen'), (4, 'Ingen')], default=4, verbose_name='Utleier'),
        ),
    ]
