# Generated by Django 2.2.28 on 2025-09-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0006_auto_20250914_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalobject',
            options={'permissions': [('add_rentalobject_ac', 'add rentalobject AC'), ('add_rentalobject_sportskom', 'add rentalobject Sportskomiteen')]},
        ),
    ]
