# Generated by Django 2.2.28 on 2025-09-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0007_auto_20250918_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalobject',
            options={'permissions': [('rentalservice.add_rentalobject_ac', 'add rentalobject AC'), ('rentalservice.add_rentalobject_sportskom', 'add rentalobject Sportskomiteen')]},
        ),
    ]
