# Generated by Django 2.2.28 on 2025-09-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0008_auto_20250918_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalobject',
            options={'permissions': [('add_rentalobject_ac', 'add rentalobject AC 2'), ('add_rentalobject_sportskom', 'add rentalobject Sportskomiteen 2')]},
        ),
    ]
