# Generated by Django 2.2.28 on 2025-09-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0011_auto_20250918_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalobject',
            options={'permissions': [('add_rentalobject_ac', 'add rentalobject AC 2'), ('add_rentalobject_sportskom', 'add rentalobject Sportskomiteen 2'), ('add_rentalobject_ac2', 'add rentalobject AC 3'), ('add_rentalobject_sportskom2', 'add rentalobject Sportskomiteen 3')]},
        ),
    ]
