# Generated by Django 2.2.28 on 2025-09-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0012_auto_20250928_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalobject',
            options={'permissions': [('add_rentalobject_ac_try2', 'add rentalobject AC forsøk 2'), ('add_rentalobject_sportskom_try2', 'add rentalobject Sportskomiteen forsøk 2')]},
        ),
    ]
