# Generated by Django 2.2.28 on 2025-09-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalservice', '0013_auto_20250928_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalobject',
            options={'permissions': [('add_rentalobject_ac', 'add rentalobject AC'), ('add_rentalobject_sportskom', 'add rentalobject Sportskomiteen'), ('change_rentalobject_ac', 'change rentalobject AC'), ('change_rentalobject_sportskom', 'change rentalobject Sportskomiteen'), ('delete_rentalobject_ac', 'delete rentalobject AC'), ('delete_rentalobject_sportskom', 'delete rentalobject Sportskomiteen')]},
        ),
    ]
