# Generated by Django 2.2.28 on 2023-09-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committees', '0003_auto_20180127_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionQuestionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Tittel')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=40, verbose_name='Påstand')),
                ('question_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electofood.ElectionQuestionForm')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(-3, 'Helt uenig'), (-2, 'Litt uenig'), (2, 'Litt enig'), (3, 'Helt enig')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electofood.ElectionQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electofood.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('electofood.answer',),
        ),
        migrations.CreateModel(
            name='CommiteeAnswer',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='electofood.Answer')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Committee')),
            ],
            bases=('electofood.answer',),
        ),
    ]
