# Generated by Django 2.2.28 on 2023-10-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electofood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionquestionform',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
