# Generated by Django 2.2.28 on 2023-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electofood', '0003_auto_20231013_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionquestionform',
            name='description',
            field=models.TextField(default='', max_length=300, verbose_name='Beskrivelse'),
        ),
    ]
