# Generated by Django 2.2.28 on 2026-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=200)),
                ('vibe', models.CharField(choices=[('positiv', 'Positiv'), ('negativ', 'Negativ'), ('usikker', 'Usikker'), ('morsom', 'Morsom')], default='usikker', max_length=20)),
            ],
        ),
    ]
