# Generated by Django 2.2.28 on 2024-09-29 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfWord', models.CharField(max_length=100, unique=True, verbose_name='Type ord')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanations', models.CharField(max_length=150, unique=True, verbose_name='Forklaring')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Dato')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Bilde')),
                ('secret', models.BooleanField(default=False, verbose_name='Hemmelig?')),
                ('word', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Ord')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Forfatter')),
                ('category', models.ManyToManyField(blank=True, to='wordlist.Category', verbose_name='Kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanations', models.CharField(max_length=150, unique=True, verbose_name='Forklaring')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Dato')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Bilde')),
                ('secret', models.BooleanField(default=False, verbose_name='Hemmelig?')),
                ('verb', models.CharField(blank=True, max_length=100, verbose_name='infinitiv')),
                ('present', models.CharField(blank=True, max_length=100, verbose_name='presens')),
                ('past', models.CharField(blank=True, max_length=100, verbose_name='preteritum')),
                ('future', models.CharField(blank=True, max_length=100, verbose_name='presens futurum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Forfatter')),
                ('category', models.ManyToManyField(blank=True, to='wordlist.Category', verbose_name='Kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanations', models.CharField(max_length=150, unique=True, verbose_name='Forklaring')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Dato')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Bilde')),
                ('secret', models.BooleanField(default=False, verbose_name='Hemmelig?')),
                ('noun', models.CharField(blank=True, max_length=100, verbose_name='ubestemt_entall')),
                ('indefinite_plural', models.CharField(blank=True, max_length=100, verbose_name='ubestemt_flertall')),
                ('definite_singular', models.CharField(blank=True, max_length=100, verbose_name='bestemt_entall')),
                ('definite_plural', models.CharField(blank=True, max_length=100, verbose_name='bestemt_flertall')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Forfatter')),
                ('category', models.ManyToManyField(blank=True, to='wordlist.Category', verbose_name='Kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanations', models.CharField(max_length=150, unique=True, verbose_name='Forklaring')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Dato')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Bilde')),
                ('secret', models.BooleanField(default=False, verbose_name='Hemmelig?')),
                ('adjective', models.CharField(blank=True, max_length=100, verbose_name='positiv')),
                ('comparative', models.CharField(blank=True, max_length=100, verbose_name='komparativ')),
                ('superlative', models.CharField(blank=True, max_length=100, verbose_name='superlativ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Forfatter')),
                ('category', models.ManyToManyField(blank=True, to='wordlist.Category', verbose_name='Kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
