# Generated by Django 2.2.28 on 2024-02-23 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('explanations', models.CharField(max_length=150, unique=True)),
                ('date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('secret', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Forfatter')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfWord', models.CharField(max_length=100, unique=True)),
                ('Words', models.ManyToManyField(blank=True, to='wordlist.Word', verbose_name='Ord')),
            ],
        ),
    ]
