# Generated by Django 2.2.28 on 2025-02-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='comparative',
            field=models.CharField(blank=True, max_length=100, verbose_name='Komparativ'),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='explanations',
            field=models.CharField(max_length=300, verbose_name='Forklaring'),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='superlative',
            field=models.CharField(blank=True, max_length=100, verbose_name='Superlativ'),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='word',
            field=models.CharField(max_length=100, unique=True, verbose_name='Positiv'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='definite_plural',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bestemt flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='definite_singular',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bestemt entall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='explanations',
            field=models.CharField(max_length=300, verbose_name='Forklaring'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='indefinite_plural',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubestemt flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='word',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ubestemt entall'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='explanations',
            field=models.CharField(max_length=300, verbose_name='Forklaring'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='future',
            field=models.CharField(blank=True, max_length=100, verbose_name='Presens futurum'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past',
            field=models.CharField(blank=True, max_length=100, verbose_name='Preteritum'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='present',
            field=models.CharField(blank=True, max_length=100, verbose_name='Presens'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='word',
            field=models.CharField(max_length=100, unique=True, verbose_name='Infinitiv'),
        ),
        migrations.AlterField(
            model_name='word',
            name='explanations',
            field=models.CharField(max_length=300, verbose_name='Forklaring'),
        ),
    ]
