# Generated by Django 2.2.28 on 2024-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Words',
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ManyToManyField(blank=True, to='wordlist.Category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='category',
            name='typeOfWord',
            field=models.CharField(max_length=100, unique=True, verbose_name='Type ord'),
        ),
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='word',
            name='explanations',
            field=models.CharField(max_length=150, unique=True, verbose_name='Forklaring'),
        ),
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='word',
            name='secret',
            field=models.BooleanField(default=False, verbose_name='Hemmelig?'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ord'),
        ),
    ]
