# Generated by Django 2.2.28 on 2024-11-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='explanations',
            field=models.CharField(max_length=300, unique=True, verbose_name='Forklaring'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='explanations',
            field=models.CharField(max_length=300, unique=True, verbose_name='Forklaring'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='explanations',
            field=models.CharField(max_length=300, unique=True, verbose_name='Forklaring'),
        ),
        migrations.AlterField(
            model_name='word',
            name='explanations',
            field=models.CharField(max_length=300, unique=True, verbose_name='Forklaring'),
        ),
    ]
