# Generated by Django 2.2.28 on 2024-04-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0002_auto_20240302_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=100, unique=True, verbose_name='infinitiv')),
                ('present', models.CharField(max_length=100, unique=True, verbose_name='presens')),
                ('past', models.CharField(max_length=100, unique=True, verbose_name='preteritum')),
                ('future', models.CharField(max_length=100, unique=True, verbose_name='presens futurum')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb', to='wordlist.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indefinite_singular', models.CharField(max_length=100, unique=True, verbose_name='ubestemt_entall')),
                ('indefinite_plural', models.CharField(max_length=100, unique=True, verbose_name='bestemt_flertall')),
                ('definite_singular', models.CharField(max_length=100, unique=True, verbose_name='ubestemt_entall')),
                ('definite_plural', models.CharField(max_length=100, unique=True, verbose_name='bestemt_flertall')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noun', to='wordlist.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.CharField(max_length=100, unique=True, verbose_name='positiv')),
                ('comparative', models.CharField(max_length=100, unique=True, verbose_name='komparativ')),
                ('superlative', models.CharField(max_length=100, unique=True, verbose_name='superlativ')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjective', to='wordlist.Word')),
            ],
        ),
    ]
