# Generated by Django 2.2.28 on 2024-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0003_adjective_noun_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='definite_plural',
            field=models.CharField(max_length=100, verbose_name='bestemt_flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='definite_singular',
            field=models.CharField(max_length=100, verbose_name='bestemt_entall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='indefinite_plural',
            field=models.CharField(max_length=100, verbose_name='ubestemt_flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='indefinite_singular',
            field=models.CharField(max_length=100, verbose_name='ubestemt_entall'),
        ),
    ]
