# Generated by Django 2.2.28 on 2024-08-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0004_auto_20240815_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjective',
            name='word',
        ),
        migrations.RemoveField(
            model_name='noun',
            name='word',
        ),
        migrations.RemoveField(
            model_name='verb',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='adjective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjective', to='wordlist.Adjective'),
        ),
        migrations.AddField(
            model_name='word',
            name='noun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noun', to='wordlist.Noun'),
        ),
        migrations.AddField(
            model_name='word',
            name='verb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verb', to='wordlist.Verb'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='definite_plural',
            field=models.CharField(max_length=100, unique=True, verbose_name='bestemt_flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='definite_singular',
            field=models.CharField(max_length=100, unique=True, verbose_name='bestemt_entall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='indefinite_plural',
            field=models.CharField(max_length=100, unique=True, verbose_name='ubestemt_flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='indefinite_singular',
            field=models.CharField(max_length=100, unique=True, verbose_name='ubestemt_entall'),
        ),
    ]
