# Generated by Django 2.2.28 on 2024-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0005_auto_20240817_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='comparative',
            field=models.CharField(max_length=100, verbose_name='komparativ'),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='positive',
            field=models.CharField(max_length=100, verbose_name='positiv'),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='superlative',
            field=models.CharField(max_length=100, verbose_name='superlativ'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='definite_plural',
            field=models.CharField(max_length=100, verbose_name='bestemt_flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='definite_singular',
            field=models.CharField(max_length=100, verbose_name='bestemt_entall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='indefinite_plural',
            field=models.CharField(max_length=100, verbose_name='ubestemt_flertall'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='indefinite_singular',
            field=models.CharField(max_length=100, verbose_name='ubestemt_entall'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='future',
            field=models.CharField(max_length=100, verbose_name='presens futurum'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='infinitive',
            field=models.CharField(max_length=100, verbose_name='infinitiv'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='past',
            field=models.CharField(max_length=100, verbose_name='preteritum'),
        ),
        migrations.AlterField(
            model_name='verb',
            name='present',
            field=models.CharField(max_length=100, verbose_name='presens'),
        ),
    ]
