# Generated by Django 2.2.28 on 2025-04-10 06:45

import ckeditor.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Navn på rett')),
                ('time', models.PositiveSmallIntegerField(default=0, verbose_name='Tid [min] ')),
                ('description', models.TextField(blank=True, default='', verbose_name='Fremgangmåte')),
                ('ingredients', ckeditor.fields.RichTextField(verbose_name='Ingredienser')),
                ('ingredient_quantity', models.CharField(blank=True, default='', max_length=30, verbose_name='Antall & Enhet til Ingrediens')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'Vegetar'), (2, 'Dessert'), (3, 'Kjøtt'), (4, 'Vegansk'), (5, 'Fisk & Skalldyr'), (6, 'Pasta & Ris'), (7, 'Suppe'), (8, 'Salater')], max_length=100), default=list, size=None, verbose_name='Kategorier')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='matlab', verbose_name='Bilde')),
                ('allowed_allergies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'Egg'), (2, 'Gluten'), (3, 'Peanøtt'), (4, 'Valnøtt'), (5, 'Andre nøtter'), (6, 'Melk/Laktose'), (7, 'Skalldyr'), (8, 'Soya')], max_length=100), default=list, size=None, verbose_name='Allergier')),
                ('expected_price', models.PositiveSmallIntegerField(default=0, verbose_name='Antatt pris')),
                ('portions', models.PositiveSmallIntegerField(default=1, verbose_name='Antall Porsjoner beregnet for')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipes_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
