# Generated by Django 2.2.28 on 2025-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matlab', '0002_auto_20250327_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='unit',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredient_quantity',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
