# Generated by Django 2.2.28 on 2025-03-29 13:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matlab', '0003_auto_20250327_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='price',
        ),
        migrations.AddField(
            model_name='recipes',
            name='allowed_allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'Egg'), (2, 'Gluten'), (3, 'Peanøtt'), (4, 'Valnøtt'), (5, 'Andre nøtter'), (6, 'Melk/Laktose'), (7, 'Skalldyr'), (8, 'Soya')], max_length=100), default=list, size=None, verbose_name='Allergier'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipes_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Fremgangmåte'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='expected_price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Antatt pris'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='matlab', verbose_name='Bilde'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='portions',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Antall Porsjoner beregnet for'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Navn på rett'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='categories',
            field=models.ManyToManyField(blank=True, to='matlab.Kategori', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredient_quantity',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Antall & Enhet til Ingrediens'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='matlab.Ingredients', verbose_name='Ingredienser'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tid [min] '),
        ),
    ]
