# Generated by Django 2.2.28 on 2025-03-29 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matlab', '0004_auto_20250329_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='categories',
        ),
        migrations.AddField(
            model_name='recipes',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'Vegetar'), (2, 'Dessert'), (3, 'Kjøtt'), (4, 'Vegansk'), (5, 'Fisk & Skalldyr'), (6, 'Pasta & Ris'), (7, 'Suppe'), (8, 'Salater')], max_length=100), default=list, size=None, verbose_name='Kategorier'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default='', to='matlab.Ingredients', verbose_name='Ingredienser'),
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
