# Generated by Django 2.2.28 on 2025-04-10 08:02

import chemie.matlab.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matlab', '0005_auto_20250410_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='allowed_allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Ingen'), (2, 'Gluten'), (3, 'Peanøtt'), (4, 'Valnøtt'), (5, 'Andre nøtter'), (6, 'Melk/Laktose'), (7, 'Skalldyr'), (8, 'Soya'), (9, 'Egg')]), default=chemie.matlab.models.get_defaul_category, size=None, verbose_name=chemie.matlab.models.get_verbose_allergy),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Ingen'), (2, 'Dessert'), (3, 'Kjøtt'), (4, 'Vegansk'), (5, 'Fisk & Skalldyr'), (6, 'Pasta & Ris'), (7, 'Suppe'), (8, 'Salater'), (9, 'Vegetar')]), default=chemie.matlab.models.get_defaul_category, size=None, verbose_name=chemie.matlab.models.get_verbose_categories),
        ),
    ]
