# Generated by Django 2.2.28 on 2025-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matlab', '0005_auto_20250329_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='matlab.Ingredients', verbose_name='Ingredienser'),
        ),
    ]
