# Generated by Django 2.2.28 on 2025-05-01 07:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matlab', '0006_auto_20250410_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=ckeditor.fields.RichTextField(verbose_name='Ingredienser (X enhet ingrediens, eks 3 ts pepper)'),
        ),
    ]
