# Generated by Django 2.1.3 on 2019-01-29 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('push_notifications', '0006_webpushdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_subscription', models.BooleanField(default=True)),
                ('news_subscription', models.BooleanField(default=True)),
                ('gcm_device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Device', to='push_notifications.GCMDevice')),
            ],
        ),
    ]
