# Generated by Django 2.1.5 on 2019-05-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_push', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('subscription_type', models.PositiveSmallIntegerField(choices=[(1, 'Coffee'), (2, 'News'), (3, 'Happy')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Eier av abonomentet')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='coffee_subscription',
        ),
    ]
