# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Epost for vervet')),
                ('start', models.DateTimeField(verbose_name='Startdato')),
                ('end', models.DateTimeField(verbose_name='Sluttdato')),
                ('position_title', models.CharField(default='Medlem', max_length=150, verbose_name='Tittel på stilling')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customprofile.Profile')),
            ],
        ),
    ]
