# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 21:13
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import smart_selects.db_fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Stillingsnavn')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Epost')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='end',
        ),
        migrations.RemoveField(
            model_name='member',
            name='position_title',
        ),
        migrations.RemoveField(
            model_name='member',
            name='start',
        ),
        migrations.AddField(
            model_name='committee',
            name='description',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2016, 12, 1, 21, 13, 25, 189606, tzinfo=utc), verbose_name='Beskrivelse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='komiteer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committees.Committee'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.Committee'),
        ),
        migrations.AddField(
            model_name='position',
            name='permission_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='committee', chained_model_field='committee', default=1, on_delete=django.db.models.deletion.CASCADE, to='committees.Position'),
            preserve_default=False,
        ),
    ]
