# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='position',
            name='can_manage_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='max_members',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Antall medlemmer'),
        ),
        migrations.AddField(
            model_name='position',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='medlem'),
        ),
        migrations.AlterField(
            model_name='position',
            name='permission_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
