# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-27 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_auto_20170811_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='medlem'),
        ),
    ]
