# Generated by Django 2.2.28 on 2024-11-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20180127_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='committee_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Kommitee'), (2, 'Undergruppe'), (3, 'Organisasjon med særskilt tilknytning')], default=1, verbose_name='gruppe_type'),
        ),
    ]
