# Generated by Django 2.2.28 on 2025-02-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committee_committee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='committee_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Komité'), (2, 'Undergruppe'), (3, 'Organisasjon med særskilt tilknytning')], default=1, verbose_name='gruppe_type'),
        ),
    ]
