# Generated by Django 2.2.28 on 2025-02-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_auto_20250129_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='rank',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Rang'),
        ),
    ]
