# Generated by Django 2.1.5 on 2020-03-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shitbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
