# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shitbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='time',
        ),
        migrations.AddField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 14, 16, 22, 11, 882182, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
