# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-04 17:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applier', models.CharField(max_length=2000, verbose_name='Søker på vegne av')),
                ('purpose', models.CharField(max_length=2000, verbose_name='Formål')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('bank_account_id', models.BigIntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Kun tall, 11 siffer', regex='^(\\d{10}|\\d{11})$')], verbose_name='Kontonummer')),
                ('bank_account_holder', models.CharField(max_length=100, verbose_name='Bankkonto innehaver')),
                ('price_range', models.IntegerField(choices=[(1, 'Under 500 kr'), (2, 'Over 500 kr')], default=1, verbose_name='Prisklasse')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='funds_application', verbose_name='Kvittering')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Innsender')),
            ],
        ),
    ]
