# Generated by Django 2.2.28 on 2025-02-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villsvin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(max_length=30)),
                ('boar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villsvin.Villsvin')),
            ],
        ),
    ]
