# Generated by Django 2.2.28 on 2025-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villsvin', '0002_korv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sykdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('life_expectancy', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='villsvin',
            name='disease',
            field=models.ManyToManyField(to='villsvin.Sykdom'),
        ),
    ]
