# Generated by Django 2.2.28 on 2025-03-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villsvin', '0003_auto_20250220_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villsvin',
            name='disease',
            field=models.ManyToManyField(blank=True, to='villsvin.Sykdom'),
        ),
    ]
