# Generated by Django 2.2.10 on 2020-10-02 12:08

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sugepodden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='sugepodden', verbose_name='Bilde'),
        ),
    ]
