# Generated by Django 2.2.10 on 2020-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugepodden', '0002_auto_20201002_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publisert'),
        ),
    ]
