# Generated by Django 2.2.10 on 2020-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugepodden', '0003_podcast_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='url',
            field=models.URLField(default='hc.ntnu.no'),
        ),
    ]
