# Generated by Django 2.2.10 on 2020-10-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugepodden', '0004_podcast_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='slug',
        ),
    ]
