# Generated by Django 2.2.10 on 2020-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugepodden', '0005_remove_podcast_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
