# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20180127_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_card', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Studentkortnummer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Innsender')),
            ],
        ),
    ]
