# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_officeapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeapplication',
            name='student_username',
            field=models.CharField(default='NOT_VALID', max_length=20, verbose_name='Studentbrukernavn'),
        ),
    ]
