# Generated by Django 2.2.28 on 2024-08-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_fundsapplication_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeapplication',
            name='student_username',
            field=models.CharField(default='NOT_VALID', max_length=50, verbose_name='Student-e-post (@ntnu.no)'),
        ),
    ]
