# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_auto_20160430_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
