# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0004_profile_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
