# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('push_notifications', '0006_webpushdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_subscription', models.BooleanField(default=True)),
                ('news_subscription', models.BooleanField(default=True)),
                ('gcm_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Device', to='push_notifications.GCMDevice')),
            ],
        ),
    ]
