# Generated by Django 2.1.3 on 2019-01-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gcm_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Device', to='push_notifications.GCMDevice'),
        ),
    ]
