# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committiees', '0002_auto_20160315_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RenameField(
            model_name='committee',
            old_name='name',
            new_name='tile',
        ),
        migrations.AddField(
            model_name='committee',
            name='email',
            field=models.EmailField(default='kek@kek.com', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='member',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committiees.Committee'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
