# Generated by Django 2.2.13 on 2021-04-04 15:29

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='is_published',
        ),
        migrations.AddField(
            model_name='interview',
            name='company_picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='corporate', verbose_name='Logo til bedriften'),
        ),
        migrations.AddField(
            model_name='interview',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(default=2000, verbose_name='Uteksamineringsår'),
        ),
    ]
