# Generated by Django 2.2.13 on 2021-04-28 09:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_auto_20210404_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKeyValuePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=300, verbose_name='Svaralternativ')),
                ('value', models.IntegerField(verbose_name='Antall')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Stilling')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Beskrivelse')),
                ('is_published', models.BooleanField(default=True, verbose_name='Er synlig')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('specializations', models.ManyToManyField(blank=True, to='corporate.Specialization', verbose_name='Aktuelle retninger')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Årstall')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=300, verbose_name='Spørsmål')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar chart'), ('pie', 'Pie chart')], default='bar', max_length=100, verbose_name='Graftype')),
            ],
        ),
        migrations.DeleteModel(
            name='JobAdvertisement',
        ),
        migrations.AddField(
            model_name='answerkeyvaluepair',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.SurveyQuestion', verbose_name='Spørsmål'),
        ),
        migrations.AddField(
            model_name='answerkeyvaluepair',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.Survey', verbose_name='Undersøkelse'),
        ),
    ]
