# Generated by Django 2.2.28 on 2023-09-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_positiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='postype',
            field=models.ManyToManyField(blank=True, to='corporate.PositionType', verbose_name='Type stilling'),
        ),
    ]
