# Generated by Django 2.2.28 on 2023-10-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0005_job_postype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiontype',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Graduatestilling'), (2, 'Sommerjobb'), (3, 'Deltidsjobb'), (4, 'Fulltidsjobb')], unique=True),
        ),
    ]
