# Generated by Django 2.2.28 on 2026-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0006_auto_20231020_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiontype',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Graduatestilling'), (2, 'Sommerjobb'), (3, 'Deltidsjobb'), (4, 'Fulltidsjobb'), (5, 'Vikariat')], unique=True),
        ),
    ]
