# Generated by Django 2.2.13 on 2021-05-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
