# Generated by Django 2.2.13 on 2021-05-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20210508_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
