# Generated by Django 2.2.13 on 2021-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_merch_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.IntegerField(),
        ),
    ]
