# Generated by Django 2.2.13 on 2022-09-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_auto_20210828_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='merch.MerchCategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='info',
            field=models.TextField(blank=True, max_length=500, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.FloatField(verbose_name='Pris'),
        ),
    ]
