# Generated by Django 2.2.13 on 2021-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_auto_20210508_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='info',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
