# Generated by Django 2.2.28 on 2023-03-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_auto_20220918_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='merch.MerchCategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='info',
            field=models.TextField(blank=True, max_length=500, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='merchcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategori'),
        ),
    ]
