# Generated by Django 2.2.28 on 2024-02-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_auto_20230316_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Navn'),
        ),
    ]
