# Generated by Django 2.2.28 on 2024-04-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0007_auto_20240223_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchcategory',
            options={'ordering': ['name']},
        ),
    ]
