# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 15:45
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedpres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Tittel')),
                ('date', models.DateTimeField(verbose_name='Dato')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('register_startdate', models.DateTimeField(verbose_name='Påmeldingen åpner')),
                ('register_deadline', models.DateTimeField(verbose_name='Påmeldingsfrist')),
                ('deregister_deadline', models.DateTimeField(verbose_name='Avmeldingsfrist')),
                ('location', models.TextField(verbose_name='Sted')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='events', verbose_name='Bilde')),
                ('sluts', models.PositiveSmallIntegerField(default=100, verbose_name='Antall plasser')),
                ('allowed_grades', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Første'), (2, 'Andre'), (3, 'Tredje'), (4, 'Fjerde'), (5, 'Femte'), (6, 'Ferdig')]), size=None)),
                ('published', models.BooleanField(default=True, verbose_name='publisert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedpresEventMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_message', to='events.Bedpres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BedpresRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('arrival_status', models.IntegerField(choices=[(1, 'Ikke satt'), (2, 'Møtt'), (3, 'Ikke møtt')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Waiting'), (3, 'Interested')], default=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Bedpres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Tittel')),
                ('date', models.DateTimeField(verbose_name='Dato')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('register_startdate', models.DateTimeField(verbose_name='Påmeldingen åpner')),
                ('register_deadline', models.DateTimeField(verbose_name='Påmeldingsfrist')),
                ('deregister_deadline', models.DateTimeField(verbose_name='Avmeldingsfrist')),
                ('location', models.TextField(verbose_name='Sted')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='events', verbose_name='Bilde')),
                ('sluts', models.PositiveSmallIntegerField(default=100, verbose_name='Antall plasser')),
                ('allowed_grades', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Første'), (2, 'Andre'), (3, 'Tredje'), (4, 'Fjerde'), (5, 'Femte'), (6, 'Ferdig')]), size=None)),
                ('published', models.BooleanField(default=True, verbose_name='publisert')),
                ('payment_information', models.TextField(max_length=500, verbose_name='Betalingsinformasjon')),
                ('price_member', models.PositiveSmallIntegerField(default=0, verbose_name='Pris, medlem')),
                ('price_not_member', models.PositiveSmallIntegerField(default=0, verbose_name='Pris, ikke-medlem')),
                ('price_companion', models.PositiveSmallIntegerField(default=0, verbose_name='Pris for følge')),
                ('companion', models.BooleanField(default=False, verbose_name='Følge')),
                ('sleepover', models.BooleanField(default=False, verbose_name='Overnatting')),
                ('night_snack', models.BooleanField(default=False, verbose_name='Nattmat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialEventMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_message', to='events.Social')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Waiting'), (3, 'Interested')], default=3)),
                ('arrival_status', models.IntegerField(choices=[(1, 'Ikke satt'), (2, 'Møtt'), (3, 'Ikke møtt')], default=1)),
                ('payment_status', models.BooleanField(default=False, verbose_name='Betalt')),
                ('sleepover', models.BooleanField(default=False, verbose_name='Overnatting')),
                ('night_snack', models.BooleanField(default=False, verbose_name='Nattmat')),
                ('companion', models.CharField(blank=True, help_text='Navn på ekstern person. Ønske om bordkavaler sendes til festkom.', max_length=40, null=True, verbose_name='Navn på følge')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Social')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),

        migrations.AddField(
            model_name='social',
            name='attendees',
            field=models.ManyToManyField(through='events.SocialEventRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='social',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedpres',
            name='attendees',
            field=models.ManyToManyField(through='events.BedpresRegistration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bedpres',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='socialeventregistration',
            unique_together=set([('event', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='bedpresregistration',
            unique_together=set([('event', 'user')]),
        ),
    ]
