# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 00:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 21, 2, 31, 55, 233921)),
        ),
        migrations.AlterField(
            model_name='event',
            name='deregister_deadline',
            field=models.DateField(default=datetime.datetime(2016, 7, 21, 2, 31, 55, 233921)),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_deadline',
            field=models.DateField(default=datetime.datetime(2016, 7, 21, 2, 31, 55, 233921)),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_startdate',
            field=models.DateField(default=datetime.datetime(2016, 7, 21, 2, 31, 55, 233921)),
        ),
    ]
