# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_model_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='limitations',
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registrationmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='registrationmessage',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registrationmessage',
            name='user',
        ),
        migrations.AlterField(
            model_name='socialeventregistration',
            name='companion',
            field=models.CharField(blank=True, help_text='Navn på ekstern person. Ønske om bordkavaler sendes til arrangør.', max_length=40, null=True, verbose_name='Navn på eksternt følge'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
        migrations.DeleteModel(
            name='Limitation',
        ),
        migrations.DeleteModel(
            name='RegistrationMessage',
        ),
    ]
