# Generated by Django 2.1.5 on 2019-03-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180927_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedpresregistration',
            name='arrival_status',
            field=models.IntegerField(choices=[(1, 'Ikke satt'), (2, 'Møtt'), (3, 'Ikke møtt')], default=1, verbose_name='Oppmøtestatus'),
        ),
        migrations.AlterField(
            model_name='socialeventregistration',
            name='arrival_status',
            field=models.IntegerField(choices=[(1, 'Ikke satt'), (2, 'Møtt'), (3, 'Ikke møtt')], default=1, verbose_name='Oppmøtestatus'),
        ),
    ]
