# Generated by Django 2.1.3 on 2019-01-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180927_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialeventregistration',
            name='companion',
            field=models.CharField(blank=True, help_text='Navn på ekstern person.             Ønske om bordkavaler sendes til arrangør.', max_length=40, null=True, verbose_name='Navn på eksternt følge'),
        ),
    ]
