# Generated by Django 2.2.9 on 2020-02-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190306_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='check_in',
            field=models.BooleanField(default=False, verbose_name='Innsjekking'),
        ),
    ]
