# Generated by Django 2.1.7 on 2019-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190306_1931'),
        ('events', '0006_auto_20190112_2152'),
    ]

    operations = [
    ]
