# Generated by Django 2.2.10 on 2021-02-15 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_social_check_in'),
    ]

    operations = [
    ]
