# Generated by Django 2.2.10 on 2021-02-11 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_social_check_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRegistrationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gruppenavn')),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Medlemmer')),
            ],
        ),
        migrations.AddField(
            model_name='bedpres',
            name='allowed_groups',
            field=models.ManyToManyField(to='events.BaseRegistrationGroup'),
        ),
        migrations.AddField(
            model_name='social',
            name='allowed_groups',
            field=models.ManyToManyField(to='events.BaseRegistrationGroup'),
        ),
    ]
