# Generated by Django 2.2.24 on 2022-09-18 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20211009_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedpres',
            name='allowed_specializations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Ingen'), (2, 'Analytisk kjemi'), (3, 'Anvendt teoretisk kjemi'), (4, 'Bioteknologi'), (5, 'Materialkjemi og energiteknologi'), (6, 'Organisk kjemi'), (7, 'Kjemisk prosessteknologi')]), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='social',
            name='allowed_specializations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Ingen'), (2, 'Analytisk kjemi'), (3, 'Anvendt teoretisk kjemi'), (4, 'Bioteknologi'), (5, 'Materialkjemi og energiteknologi'), (6, 'Organisk kjemi'), (7, 'Kjemisk prosessteknologi')]), blank=True, null=True, size=None),
        ),
    ]
