# Generated by Django 2.2.28 on 2023-10-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20211009_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedpres',
            name='tentative',
            field=models.BooleanField(default=False, verbose_name='tentativ'),
        ),
        migrations.AddField(
            model_name='social',
            name='tentative',
            field=models.BooleanField(default=False, verbose_name='tentativ'),
        ),
    ]
