# Generated by Django 2.2.28 on 2025-04-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20231020_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialeventregistration',
            name='can_eat_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Kan spise vegetar'),
        ),
    ]
