# Generated by Django 2.2.28 on 2025-01-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20231020_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedpresregistration',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Waiting'), (3, 'Interested'), (4, 'Selling'), (5, 'Inactive')], default=3),
        ),
        migrations.AlterField(
            model_name='socialeventregistration',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Waiting'), (3, 'Interested'), (4, 'Selling'), (5, 'Inactive')], default=3),
        ),
        migrations.CreateModel(
            name='SocialResellReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resell_payment_status', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('response_time', models.DurationField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('buyer_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sosial_resell_receipt_buyer', to='events.SocialEventRegistration')),
                ('seller_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sosial_resell_receipt_seller', to='events.SocialEventRegistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
