# Generated by Django 2.2.28 on 2024-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20180127_0949'),
        ('events', '0011_auto_20231020_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='committee',
        ),
        migrations.AddField(
            model_name='social',
            name='committee',
            field=models.ManyToManyField(null=True, to='committees.Committee'),
        ),
    ]
