# Generated by Django 2.2.28 on 2026-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20231020_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='smallroom',
            field=models.BooleanField(default=False, verbose_name='Liten sal'),
        ),
        migrations.AddField(
            model_name='socialeventregistration',
            name='smallroom',
            field=models.BooleanField(default=False, verbose_name='Liten sal'),
        ),
    ]
