# Generated by Django 2.2.28 on 2026-01-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20260122_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='smallroom',
            field=models.BooleanField(default=False, verbose_name='Storfest 2026'),
        ),
        migrations.AlterField(
            model_name='socialeventregistration',
            name='smallroom',
            field=models.BooleanField(default=False, verbose_name='Jeg kan sitte på lillerommet'),
        ),
    ]
