# Generated by Django 2.2.28 on 2025-01-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20250114_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedpresregistration',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Waiting'), (3, 'Interested'), (4, 'Sold'), (5, 'Inactive'), (6, 'Offered')], default=3),
        ),
        migrations.AlterField(
            model_name='socialeventregistration',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Waiting'), (3, 'Interested'), (4, 'Sold'), (5, 'Inactive'), (6, 'Offered')], default=3),
        ),
    ]
