# Generated by Django 2.2.28 on 2024-01-24 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refoundrequest',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Tilbakebetalt'),
        ),
        migrations.AlterField(
            model_name='refound',
            name='date',
            field=models.DateField(verbose_name='Utleggsdato'),
        ),
        migrations.AlterField(
            model_name='refound',
            name='event',
            field=models.CharField(max_length=50, verbose_name='Hensikt'),
        ),
        migrations.AlterField(
            model_name='refound',
            name='image',
            field=models.ImageField(upload_to='receipts', verbose_name='Kvittering'),
        ),
        migrations.AlterField(
            model_name='refound',
            name='item',
            field=models.CharField(max_length=500, verbose_name='Vare'),
        ),
        migrations.AlterField(
            model_name='refound',
            name='price',
            field=models.IntegerField(verbose_name='Pris'),
        ),
        migrations.AlterField(
            model_name='refound',
            name='store',
            field=models.CharField(max_length=50, verbose_name='Kjøpssted'),
        ),
        migrations.AlterField(
            model_name='refoundrequest',
            name='account_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Kontonummer'),
        ),
    ]
