# Generated by Django 2.2.28 on 2024-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refound', '0002_auto_20240124_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refoundrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='refoundrequest',
            name='paystatus',
            field=models.SmallIntegerField(choices=[(1, 'Avslått'), (2, 'Under behandling'), (3, 'Tilbakebetalt')], default=2, verbose_name='Tilbakebetalt'),
        ),
    ]
