# Generated by Django 2.2.28 on 2023-03-16 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='Er åpent')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='cgp')),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_username', models.CharField(max_length=50, unique=True)),
                ('real_name', models.CharField(max_length=50)),
                ('song_name', models.CharField(blank=True, max_length=100)),
                ('has_voted', models.BooleanField(default=False, verbose_name='Har stemt')),
                ('cgp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgp.CGP')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cgp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_vote', models.BooleanField(default=False)),
                ('vote', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='CGP_Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_members', models.PositiveSmallIntegerField(default=1, verbose_name='Antall medlemmer')),
                ('can_manage_country', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgp.Group')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='medlem')),
            ],
        ),
    ]
