# Generated by Django 2.2.28 on 2023-01-06 23:26

from django.conf import settings
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('real_name', models.CharField(max_length=50)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='cgp')),
                ('has_voted', models.BooleanField(default=False, verbose_name='Har stemt')),
                ('vote', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='medlem')),
            ],
        ),
        migrations.CreateModel(
            name='CGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='Er åpent')),
                ('countries', models.ManyToManyField(blank=True, to='cgp.Country', verbose_name='country')),
            ],
        ),
    ]
