# Generated by Django 2.2.28 on 2023-04-01 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, verbose_name='Er åpent')),
                ('year', models.IntegerField(unique=True, verbose_name='År')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True, verbose_name='Navn')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='cgp', verbose_name='Bilde')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='Gruppenavn')),
                ('song_name', models.CharField(blank=True, max_length=100, verbose_name='Sangtittel')),
                ('audience', models.BooleanField(default=False, verbose_name='Publikum')),
                ('has_voted', models.BooleanField(default=False, verbose_name='Har stemt')),
                ('cgp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgp.CGP')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cgp.Country', verbose_name='Land')),
                ('group_leaders', models.ManyToManyField(blank=True, related_name='group_leaders', to=settings.AUTH_USER_MODEL, verbose_name='Ledere')),
                ('group_members', models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL, verbose_name='Medlemmer')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_vote', models.BooleanField(default=False)),
                ('vote', models.TextField(blank=True)),
                ('failureprize_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failurevote', to='cgp.Group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgp.Group')),
                ('showprize_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showvote', to='cgp.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
