# Generated by Django 2.2.28 on 2023-03-16 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cgp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CGP_Position',
            new_name='CgpPosition',
        ),
    ]
