# Generated by Django 2.2.28 on 2023-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='song_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
