# Generated by Django 2.2.28 on 2023-03-16 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0002_auto_20230316_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgp',
            name='year',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 3, 16, 16, 14, 25, 505147, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
