# Generated by Django 2.2.28 on 2023-01-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0002_country_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='song_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
