# Generated by Django 2.2.28 on 2023-01-13 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cgp', '0003_auto_20230109_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='users',
        ),
        migrations.CreateModel(
            name='CountryPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Stillingsnavn')),
                ('max_members', models.PositiveSmallIntegerField(default=1, verbose_name='Antall medlemmer')),
                ('can_manage_country', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgp.Country')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='medlem')),
            ],
        ),
    ]
