# Generated by Django 2.2.28 on 2023-01-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0004_auto_20230113_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryposition',
            name='title',
        ),
    ]
