# Generated by Django 2.2.28 on 2023-03-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0004_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
