# Generated by Django 2.2.28 on 2023-03-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cgp', '0006_vote_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_vote', models.BooleanField(default=False)),
                ('vote', models.TextField(blank=True)),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(1, 'showpris'), (2, 'fiaskopris')], default=1, verbose_name='Klassetrinn')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgp.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
