# Generated by Django 2.2.28 on 2023-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0007_extravote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extravote',
            name='vote_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'showpris'), (2, 'fiaskopris')], default=1, verbose_name='Pris'),
        ),
    ]
