# Generated by Django 2.2.28 on 2023-03-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0008_auto_20230329_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extravote',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='cgp.Group'),
        ),
        migrations.RemoveField(
            model_name='extravote',
            name='vote',
        ),
        migrations.AddField(
            model_name='extravote',
            name='vote',
            field=models.ManyToManyField(blank=True, related_name='extravote', to='cgp.Group'),
        ),
    ]
