# Generated by Django 2.2.28 on 2023-03-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0010_auto_20230329_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='failureprize_group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='failurevote', to='cgp.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='showprize_group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='showvote', to='cgp.Group'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExtraVote',
        ),
    ]
