# Generated by Django 2.2.28 on 2023-03-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0011_auto_20230330_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='failureprize_group',
            new_name='failureprize_vote',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='showprize_group',
            new_name='showprize_vote',
        ),
    ]
