# Generated by Django 2.2.28 on 2023-03-31 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cgp', '0014_auto_20230330_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_leaders',
            field=models.ManyToManyField(related_name='group_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CgpPosition',
        ),
    ]
