# Generated by Django 2.2.28 on 2023-03-31 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0015_auto_20230331_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_leaders',
            field=models.ManyToManyField(blank=True, related_name='group_leaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
