# Generated by Django 2.2.28 on 2023-03-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0016_auto_20230331_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_username',
        ),
        migrations.AddField(
            model_name='group',
            name='audience',
            field=models.BooleanField(default=False, verbose_name='Publikum'),
        ),
    ]
