# Generated by Django 2.2.28 on 2023-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0017_auto_20230331_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
