# Generated by Django 2.2.28 on 2023-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0018_auto_20230331_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='hei', unique=True),
            preserve_default=False,
        ),
    ]
