# Generated by Django 2.2.28 on 2023-03-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0019_auto_20230331_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgp',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
