# Generated by Django 2.2.28 on 2023-03-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0020_auto_20230331_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgp',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
