# Generated by Django 2.2.28 on 2023-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0021_auto_20230331_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgp',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='År'),
        ),
    ]
