# Generated by Django 2.2.28 on 2023-03-31 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0022_auto_20230331_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='cgp', verbose_name='Bilde'),
        ),
        migrations.AlterField(
            model_name='group',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cgp.Country', verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_leaders',
            field=models.ManyToManyField(blank=True, related_name='group_leaders', to=settings.AUTH_USER_MODEL, verbose_name='Leder'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to=settings.AUTH_USER_MODEL, verbose_name='Medlemmer'),
        ),
        migrations.AlterField(
            model_name='group',
            name='real_name',
            field=models.CharField(max_length=50, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='group',
            name='song_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sangtittel'),
        ),
    ]
