# Generated by Django 2.2.28 on 2023-03-31 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgp', '0023_auto_20230331_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_leaders',
            field=models.ManyToManyField(blank=True, related_name='group_leaders', to=settings.AUTH_USER_MODEL, verbose_name='Ledere'),
        ),
        migrations.AlterField(
            model_name='group',
            name='real_name',
            field=models.CharField(max_length=50, verbose_name='Gruppenavn'),
        ),
    ]
