# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
