# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160605_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsPost',
            new_name='Article',
        ),
    ]
