# Generated by Django 2.2.28 on 2023-03-16 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_push', '0002_auto_20190530_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='avatars')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('endorser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'Første'), (2, 'Andre'), (3, 'Tredje'), (4, 'Fjerde'), (5, 'Femte'), (6, 'Ferdig')], default=1, verbose_name='Klassetrinn')),
                ('start_year', models.PositiveSmallIntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2023, verbose_name='Startår')),
                ('end_year', models.PositiveSmallIntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030)], default=2028, verbose_name='Estimert ferdig')),
                ('specialization', models.PositiveSmallIntegerField(choices=[(1, 'Ingen'), (2, 'Analytisk kjemi'), (3, 'Anvendt teoretisk kjemi'), (4, 'Bioteknologi'), (5, 'Materialkjemi og energiteknologi'), (6, 'Organisk kjemi'), (7, 'Kjemisk prosessteknologi')], default=1, verbose_name='Spesialisering')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Matallergi')),
                ('relationship_status', models.PositiveSmallIntegerField(choices=[(1, 'Singel'), (2, 'Opptatt'), (3, 'Hemmelig!')], default=1, verbose_name='Samlivsstatus')),
                ('phone_number', models.BigIntegerField(verbose_name='Mobilnummer')),
                ('access_card', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='EM nummer (ikke ta med 0 dersom det er første siffer)')),
                ('image_primary', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='avatars')),
                ('image_secondary', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='avatars')),
                ('address', models.CharField(max_length=200, verbose_name='Adresse')),
                ('approved_terms', models.BooleanField(default=False)),
                ('voted', models.BooleanField(default=False)),
                ('eligible_for_voting', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('devices', models.ManyToManyField(blank=True, to='web_push.Device', verbose_name='Push notification-enheter')),
                ('medals', models.ManyToManyField(blank=True, to='customprofile.Medal', verbose_name='Digidaljer')),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='customprofile.Membership')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='profile', to='web_push.Subscription', verbose_name='Abonnomenter på push-varsler')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
            options={
                'permissions': (('can_edit_access_card', 'Can change access card of profiles'), ('refill_balance', 'Can refill balance')),
            },
        ),
    ]
