# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'Første'), (2, 'Andre'), (3, 'Tredje'), (4, 'Fjerde'), (5, 'Femte'), (6, 'Ferdig')], default=1)),
                ('allergies', models.CharField(max_length=200)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('phone_number', models.PositiveSmallIntegerField()),
                ('access_card', models.CharField(max_length=10)),
                ('image_primary', sorl.thumbnail.fields.ImageField(upload_to='avatars')),
                ('image_secondary', sorl.thumbnail.fields.ImageField(upload_to='avatars')),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
