# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0002_auto_20160515_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_card',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
