# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0002_unique_user_access_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_card',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Studentkortnummer'),
        ),
    ]
