# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0002_auto_20160515_0007'),
        ('customprofile', '0002_auto_20160515_1251'),
    ]

    operations = [
    ]
