# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0003_auto_20160526_1745'),
        ('customprofile', '0003_auto_20160521_0008'),
    ]

    operations = [
    ]
