# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0003_auto_20170920_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_terms',
            field=models.BooleanField(default=False),
        ),
    ]
