# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 10:05
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0004_profile_approved_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_primary',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_secondary',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
