# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Singel'), (2, 'Opptatt'), (3, 'Det er komplisert...'), (4, 'Gjett ;)'), (5, 'Hemmelig!')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.CharField(max_length=200, verbose_name='Allergier'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='end_year',
            field=models.PositiveSmallIntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2021, verbose_name='Slutt år'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Første'), (2, 'Andre'), (3, 'Tredje'), (4, 'Fjerde'), (5, 'Femte'), (6, 'Ferdig')], default=1, verbose_name='Klassetrinn'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_year',
            field=models.PositiveSmallIntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2016, verbose_name='Startsår'),
        ),
    ]
