# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Singel'), (2, 'Opptatt'), (3, 'Det er komplisert...'), (4, 'Gjett ;)'), (5, 'Hemmelig!')], default=1),
        ),
    ]
