# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0005_profile_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('refill_balance', 'Can refill balance'),)},
        ),
    ]
