# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0005_profile_relationship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='access_card',
            field=models.CharField(max_length=10, unique=True, verbose_name='Studentkortnummer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Matallergi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveSmallIntegerField(verbose_name='Mobilnummer'),
        ),
    ]
