# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0005_auto_20180815_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
