# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0005_auto_20160616_1418'),
        ('customprofile', '0006_auto_20160606_2216'),
        ('customprofile', '0003_auto_20160521_0008'),
    ]

    operations = [
    ]
