# Generated by Django 2.1.3 on 2019-01-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0007_auto_20190112_2152'),
        ('customprofile', '0007_auto_20190115_2023'),
    ]

    operations = [
    ]
