# Generated by Django 2.1.3 on 2019-02-05 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0007_auto_20190115_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_edit_access_card', 'Can change access card of profiles'),)},
        ),
        migrations.AddField(
            model_name='profile',
            name='eligible_for_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Bruker'),
        ),
    ]
