# Generated by Django 2.1.5 on 2019-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0008_auto_20190205_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_edit_access_card', 'Can change access card of profiles'), ('refill_balance', 'Can refill balance'))},
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
