# Generated by Django 2.1.7 on 2019-03-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0008_merge_20190117_2018'),
        ('customprofile', '0008_auto_20190205_1009'),
    ]

    operations = [
    ]
