# Generated by Django 2.1.5 on 2019-05-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_push', '0002_auto_20190530_1402'),
        ('customprofile', '0009_auto_20190219_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='devices',
            field=models.ManyToManyField(blank=True, to='web_push.Device', verbose_name='Push notification-enheter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='profile', to='web_push.Subscription', verbose_name='Abonnomenter på push-varsler'),
        ),
    ]
