# Generated by Django 2.2.13 on 2022-09-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0013_auto_20220324_1352'),
        ('customprofile', '0013_auto_20220304_1513'),
    ]

    operations = [
    ]
