# Generated by Django 2.2.28 on 2023-10-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0016_auto_20230923_1311'),
        ('customprofile', '0016_auto_20230928_1352'),
    ]

    operations = [
    ]
