# Generated by Django 2.2.28 on 2024-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0018_auto_20240104_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Singel'), (2, 'Opptatt'), (3, 'Hemmelig!'), (4, 'HC incest')], default=1, verbose_name='Samlivsstatus'),
        ),
    ]
