# Generated by Django 2.2.28 on 2024-10-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0020_auto_20240811_1157'),
        ('customprofile', '0019_auto_20240223_1228'),
    ]

    operations = [
    ]
