# Generated by Django 2.2.28 on 2025-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0021_auto_20250129_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
