# Generated by Django 2.2.28 on 2025-04-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0022_registerpagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpagestatus',
            name='name',
            field=models.CharField(default='Registreringsside', max_length=100),
        ),
    ]
