# Generated by Django 2.2.28 on 2025-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customprofile', '0023_registerpagestatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_card',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ES nummer (ikke ta med 0 dersom det er første siffer)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adresse (Kan være i eller utenfor Trondheim)'),
        ),
    ]
