# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:45
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('picturecarousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(upload_to='kontorbilder'),
        ),
    ]
