# Generated by Django 2.1.5 on 2020-01-18 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('picturecarousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_pictures', to=settings.AUTH_USER_MODEL),
        ),
    ]
