# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField(blank=True, default=models.DateTimeField(auto_now_add=True))),
                ('event_name', models.CharField(max_length=120)),
            ],
        ),
    ]
