# Generated by Django 2.2.28 on 2026-03-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='Title')),
                ('cover', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='shitbox', verbose_name='Cover')),
                ('date', models.DateTimeField(verbose_name='Dato')),
                ('used', models.BooleanField(default=False)),
                ('cost', models.SmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Innsender')),
            ],
        ),
    ]
