# Generated by Django 2.2.28 on 2026-03-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Rollenavn')),
                ('rank', models.PositiveSmallIntegerField(default=1, verbose_name='Rang')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Navn')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Opprettet')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Navn')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Nivå')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Innmeldt')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Totalt investert')),
                ('is_founder', models.BooleanField(default=False, verbose_name='Grunnlegger')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruits', to='test_app_2.Member', verbose_name='Rekruttert av')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app_2.Role', verbose_name='Rolle')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='test_app_2.Scheme', verbose_name='Scheme')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bruker')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Beløp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrert')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Notat')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='test_app_2.Member', verbose_name='Medlem')),
            ],
        ),
    ]
