# Generated by Django 2.2.28 on 2026-03-09 14:36

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=1000)),
                ('age', models.PositiveIntegerField()),
                ('dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Cult name')),
                ('cover', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='shitbox', verbose_name='Cover')),
                ('motto', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(verbose_name='Dato')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_executive', models.BooleanField()),
                ('executive', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_app_2.Cult')),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('gold', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app_2.Cult')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sacrifice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=1000)),
                ('age', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('sacrifices', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_app_2.Cult')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='bruker',
            name='er_leder',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_app_2.Role'),
        ),
        migrations.AddField(
            model_name='bruker',
            name='tilhører',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app_2.Cult'),
        ),
    ]
