# Generated by Django 2.2.28 on 2026-04-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='image',
        ),
        migrations.AddField(
            model_name='refund',
            name='file',
            field=models.FileField(default='', upload_to='receipts', verbose_name='Kvittering / Skjema for Kjøregodtgjørelse'),
            preserve_default=False,
        ),
    ]
