# Generated by Django 2.2.28 on 2026-09-07 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='file',
            field=models.FileField(upload_to='receipts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.webp', '.jfif', '.pdf'])], verbose_name='Kvittering / Skjema for Kjøregodtgjørelse'),
        ),
    ]
