# Generated by Django 2.2.28 on 2026-09-19 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='file',
        ),
        migrations.AddField(
            model_name='refund',
            name='image',
            field=models.FileField(db_column='image', null=True, upload_to='receipts', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'jfif', 'pdf'])], verbose_name='Kvittering / Skjema for Kjøregodtgjørelse'),
        ),
    ]
