# Generated by Django 2.2.28 on 2023-03-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktype',
            name='Stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Stocktype'),
            preserve_default=False,
        ),
    ]
