# Generated by Django 2.2.28 on 2023-03-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20230318_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock',
            new_name='stocktype',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='amount',
        ),
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Portfolio'),
        ),
        migrations.AddField(
            model_name='stocktype',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
