# Generated by Django 2.2.28 on 2023-03-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20230318_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktype',
            name='amount',
        ),
    ]
