# Generated by Django 2.2.28 on 2023-03-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stocktype_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Stock',
        ),
        migrations.AddField(
            model_name='history',
            name='stocktype',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Stocktype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Portfolio'),
        ),
    ]
