# Generated by Django 2.2.28 on 2023-03-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20230322_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='volume',
        ),
        migrations.AlterField(
            model_name='history',
            name='stocktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stocktype'),
        ),
    ]
