name: LINTING

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Black Code Formatter
      uses: HoiskolensChemikerforening/black-action #lgeiger/black-action@v1.0.1
      with:
          args: "./chemie --check"
