name: Build Dockerfiles on Pull Request

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]

jobs:
  build:
    name: Build Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Show worktree
        run: ls

      - name: Build with docker-compose
        run: docker-compose up -d --build