name: Build Dockerfiles on Pull Request

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]

jobs:
  build:
    name: Build Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create an empty .env file
        run: touch .env

      - name: Create an empty ssh_key
        run: touch ssh_key

      - name: Build with docker-compose
        run: docker-compose up -d --build
