name: Run Python Tests

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: hc_chemie
          POSTGRES_USER: hc_chemie
          POSTGRES_PASSWORD: passord
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
    - name: Test with pytest
      env:
          # postgres://<username>:<password>@<host>/<dbname>
          DATABASE_URL: 'postgres://hc_chemie:passord@127.0.0.1:${{ job.services.postgres.ports[5432] }}/hc_chemie'
      run: |
        pytest -c pytest.ini
